// AUTO-GENERATED by scripts/gen-nav-pages.mjs from src/components/sidebar.tsx. Do not edit by hand.
export type NavPage = { key: string; path: string; label: string };
export type NavModule = { module: string; pages: NavPage[] };

export const NAV_MODULES: NavModule[] = [
  {
    "module": "General",
    "pages": [
      {
        "key": "dashboard",
        "path": "/dashboard",
        "label": "Global Dashboard"
      }
    ]
  },
  {
    "module": "Identity & Access",
    "pages": [
      {
        "key": "iam.dashboard",
        "path": "/iam/dashboard",
        "label": "Overview"
      },
      {
        "key": "iam.organizations",
        "path": "/iam/organizations",
        "label": "Organizations"
      },
      {
        "key": "iam.users",
        "path": "/iam/users",
        "label": "Users"
      },
      {
        "key": "iam.roles",
        "path": "/iam/roles",
        "label": "Roles"
      },
      {
        "key": "iam.audit-logs",
        "path": "/iam/audit-logs",
        "label": "Audit Logs"
      },
      {
        "key": "iam.api-keys",
        "path": "/iam/api-keys",
        "label": "API Keys"
      }
    ]
  },
  {
    "module": "Product & Catalog",
    "pages": [
      {
        "key": "catalog.dashboard",
        "path": "/catalog/dashboard",
        "label": "Overview"
      },
      {
        "key": "catalog.items",
        "path": "/catalog/items",
        "label": "Catalog Items"
      },
      {
        "key": "catalog.inventory-import",
        "path": "/catalog/inventory-import",
        "label": "Inventory Import"
      },
      {
        "key": "catalog.variants",
        "path": "/catalog/variants",
        "label": "Variants"
      },
      {
        "key": "catalog.product-media",
        "path": "/catalog/product-media",
        "label": "Product Media"
      },
      {
        "key": "catalog.bundles",
        "path": "/catalog/bundles",
        "label": "Bundles"
      },
      {
        "key": "catalog.channel-mappings",
        "path": "/catalog/channel-mappings",
        "label": "Channel Mappings"
      },
      {
        "key": "catalog.import-channels",
        "path": "/catalog/import-channels",
        "label": "Import Channels"
      },
      {
        "key": "catalog.wordpress-channels",
        "path": "/catalog/wordpress-channels",
        "label": "WordPress Channels"
      },
      {
        "key": "catalog.epos-channels",
        "path": "/catalog/epos-channels",
        "label": "EPOS Channels"
      },
      {
        "key": "catalog.price-lists",
        "path": "/catalog/price-lists",
        "label": "Price Lists"
      },
      {
        "key": "catalog.promotional-prices",
        "path": "/catalog/promotional-prices",
        "label": "Promotional Prices"
      },
      {
        "key": "catalog.tax-codes",
        "path": "/catalog/tax-codes",
        "label": "Tax Codes"
      },
      {
        "key": "catalog.compliance-documents",
        "path": "/catalog/compliance-documents",
        "label": "Compliance Documents"
      }
    ]
  },
  {
    "module": "Inventory",
    "pages": [
      {
        "key": "inventory.dashboard",
        "path": "/inventory/dashboard",
        "label": "Overview"
      },
      {
        "key": "inventory.warehouses",
        "path": "/inventory/warehouses",
        "label": "Warehouses"
      },
      {
        "key": "inventory.bins",
        "path": "/inventory/bins",
        "label": "Bins"
      },
      {
        "key": "inventory.stock-items",
        "path": "/inventory/stock-items",
        "label": "Stock Items"
      },
      {
        "key": "inventory.suppliers",
        "path": "/inventory/suppliers",
        "label": "Suppliers"
      },
      {
        "key": "inventory.purchase-orders",
        "path": "/inventory/purchase-orders",
        "label": "Purchase Orders"
      },
      {
        "key": "inventory.asn",
        "path": "/inventory/asn",
        "label": "ASN"
      },
      {
        "key": "inventory.grn",
        "path": "/inventory/grn",
        "label": "GRN"
      },
      {
        "key": "inventory.stock-transfers",
        "path": "/inventory/stock-transfers",
        "label": "Stock Transfers"
      },
      {
        "key": "inventory.stock-adjustments",
        "path": "/inventory/stock-adjustments",
        "label": "Stock Adjustments"
      },
      {
        "key": "inventory.cycle-counts",
        "path": "/inventory/cycle-counts",
        "label": "Cycle Counts"
      }
    ]
  },
  {
    "module": "Orders & Customers",
    "pages": [
      {
        "key": "orders.dashboard",
        "path": "/orders/dashboard",
        "label": "Overview"
      },
      {
        "key": "orders.customers",
        "path": "/orders/customers",
        "label": "Customers"
      },
      {
        "key": "orders.orders",
        "path": "/orders/orders",
        "label": "Orders"
      },
      {
        "key": "orders.returns",
        "path": "/orders/returns",
        "label": "Returns"
      },
      {
        "key": "orders.channel-sync",
        "path": "/orders/channel-sync",
        "label": "Channel Sync"
      }
    ]
  },
  {
    "module": "B2B Sale Channel",
    "pages": [
      {
        "key": "b2b.dashboard",
        "path": "/b2b/dashboard",
        "label": "Overview"
      },
      {
        "key": "b2b.products",
        "path": "/b2b/products",
        "label": "Products"
      },
      {
        "key": "b2b.retailers",
        "path": "/b2b/retailers",
        "label": "Retailers"
      },
      {
        "key": "b2b.orders",
        "path": "/b2b/orders",
        "label": "Orders"
      },
      {
        "key": "b2b.shipments",
        "path": "/b2b/shipments",
        "label": "Shipments"
      },
      {
        "key": "b2b.shipping-methods",
        "path": "/b2b/shipping-methods",
        "label": "Shipping Methods"
      },
      {
        "key": "b2b.credit-referrals",
        "path": "/b2b/credit-referrals",
        "label": "Credit & Referrals"
      },
      {
        "key": "marketing.affiliates",
        "path": "/marketing/affiliates",
        "label": "Affiliates & Referrals"
      },
      {
        "key": "b2b.pricing",
        "path": "/b2b/pricing",
        "label": "Pricing"
      },
      {
        "key": "b2b.settings",
        "path": "/b2b/settings",
        "label": "Settings"
      },
      {
        "key": "finance.payment-dashboard",
        "path": "/finance/payment-dashboard",
        "label": "Payment Dashboard"
      }
    ]
  },
  {
    "module": "Payments & Invoicing",
    "pages": [
      {
        "key": "finance.dashboard",
        "path": "/finance/dashboard",
        "label": "Overview"
      },
      {
        "key": "finance.invoices",
        "path": "/finance/invoices",
        "label": "Invoices"
      },
      {
        "key": "finance.payment-dashboard",
        "path": "/finance/payment-dashboard",
        "label": "Payment Dashboard"
      },
      {
        "key": "finance.payments",
        "path": "/finance/payments",
        "label": "Payments"
      },
      {
        "key": "finance.gateways",
        "path": "/finance/gateways",
        "label": "Payment Gateways"
      },
      {
        "key": "finance.chart-of-accounts",
        "path": "/finance/chart-of-accounts",
        "label": "Chart of Accounts"
      },
      {
        "key": "finance.ledger-accounts",
        "path": "/finance/ledger-accounts",
        "label": "Ledger Accounts"
      },
      {
        "key": "finance.cost-centers",
        "path": "/finance/cost-centers",
        "label": "Cost Centers"
      },
      {
        "key": "finance.fiscal-periods",
        "path": "/finance/fiscal-periods",
        "label": "Fiscal Periods"
      },
      {
        "key": "finance.journal-entries",
        "path": "/finance/journal-entries",
        "label": "Journal Entries"
      },
      {
        "key": "finance.bank-accounts",
        "path": "/finance/bank-accounts",
        "label": "Bank Accounts"
      },
      {
        "key": "finance.bank-transactions",
        "path": "/finance/bank-transactions",
        "label": "Bank Transactions"
      },
      {
        "key": "finance.vat-returns",
        "path": "/finance/vat-returns",
        "label": "VAT Returns"
      },
      {
        "key": "finance.budget-lines",
        "path": "/finance/budget-lines",
        "label": "Budget Lines"
      }
    ]
  },
  {
    "module": "Finance & Accounting",
    "pages": [
      {
        "key": "accounting.dashboard",
        "path": "/accounting/dashboard",
        "label": "Dashboard"
      },
      {
        "key": "accounting.sales",
        "path": "/accounting/sales",
        "label": "Sales / Invoicing"
      },
      {
        "key": "accounting.purchases",
        "path": "/accounting/purchases",
        "label": "Purchases / Bills"
      },
      {
        "key": "accounting.banking",
        "path": "/accounting/banking",
        "label": "Banking"
      },
      {
        "key": "accounting.ledger",
        "path": "/accounting/ledger",
        "label": "Accounting"
      },
      {
        "key": "accounting.vat",
        "path": "/accounting/vat",
        "label": "VAT"
      },
      {
        "key": "accounting.payroll",
        "path": "/accounting/payroll",
        "label": "Payroll"
      },
      {
        "key": "accounting.expenses",
        "path": "/accounting/expenses",
        "label": "Expenses"
      },
      {
        "key": "accounting.fixed-assets",
        "path": "/accounting/fixed-assets",
        "label": "Fixed Assets"
      },
      {
        "key": "accounting.tax",
        "path": "/accounting/tax",
        "label": "Tax"
      },
      {
        "key": "accounting.reporting",
        "path": "/accounting/reporting",
        "label": "Reporting"
      },
      {
        "key": "accounting.documents",
        "path": "/accounting/documents",
        "label": "Documents"
      },
      {
        "key": "accounting.audit-trail",
        "path": "/accounting/audit-trail",
        "label": "Audit Trail"
      },
      {
        "key": "accounting.settings",
        "path": "/accounting/settings",
        "label": "Settings"
      }
    ]
  },
  {
    "module": "HR & Payroll",
    "pages": [
      {
        "key": "hr.dashboard",
        "path": "/hr/dashboard",
        "label": "Dashboard"
      },
      {
        "key": "hr.employees",
        "path": "/hr/employees",
        "label": "Employees"
      },
      {
        "key": "hr.immigration",
        "path": "/hr/immigration",
        "label": "Immigration & RTW"
      },
      {
        "key": "hr.leave",
        "path": "/hr/leave",
        "label": "Leave"
      },
      {
        "key": "hr.attendance",
        "path": "/hr/attendance",
        "label": "Attendance"
      },
      {
        "key": "hr.payroll",
        "path": "/hr/payroll",
        "label": "Payroll"
      },
      {
        "key": "hr.pension",
        "path": "/hr/pension",
        "label": "Pension"
      },
      {
        "key": "hr.documents",
        "path": "/hr/documents",
        "label": "Documents"
      },
      {
        "key": "hr.recruitment",
        "path": "/hr/recruitment",
        "label": "Recruitment"
      },
      {
        "key": "hr.onboarding",
        "path": "/hr/onboarding",
        "label": "Onboarding"
      },
      {
        "key": "hr.self-service",
        "path": "/hr/self-service",
        "label": "Self-service"
      },
      {
        "key": "hr.reports",
        "path": "/hr/reports",
        "label": "Reports & Compliance"
      }
    ]
  },
  {
    "module": "Analytics & Reporting",
    "pages": [
      {
        "key": "analytics.dashboard",
        "path": "/analytics/dashboard",
        "label": "Overview"
      },
      {
        "key": "analytics.reports",
        "path": "/analytics/reports",
        "label": "Reports"
      },
      {
        "key": "analytics.scheduled-reports",
        "path": "/analytics/scheduled-reports",
        "label": "Scheduled"
      },
      {
        "key": "analytics.exports",
        "path": "/analytics/exports",
        "label": "Data Exports"
      }
    ]
  },
  {
    "module": "Fulfillment & 3PL",
    "pages": [
      {
        "key": "fulfillment.dashboard",
        "path": "/fulfillment/dashboard",
        "label": "Overview"
      },
      {
        "key": "fulfillment.pick-pack",
        "path": "/fulfillment/pick-pack",
        "label": "Pick/Pack"
      },
      {
        "key": "fulfillment.shipments",
        "path": "/fulfillment/shipments",
        "label": "Shipments"
      },
      {
        "key": "fulfillment.tracking",
        "path": "/fulfillment/tracking",
        "label": "Tracking"
      }
    ]
  },
  {
    "module": "System & Config",
    "pages": [
      {
        "key": "system.dashboard",
        "path": "/system/dashboard",
        "label": "Overview"
      },
      {
        "key": "system.settings",
        "path": "/system/settings",
        "label": "Settings"
      },
      {
        "key": "system.templates",
        "path": "/system/templates",
        "label": "Templates"
      },
      {
        "key": "system.webhooks",
        "path": "/system/webhooks",
        "label": "Webhooks"
      }
    ]
  },
  {
    "module": "CRM & Customer Service",
    "pages": [
      {
        "key": "crm.dashboard",
        "path": "/crm/dashboard",
        "label": "Overview"
      },
      {
        "key": "crm.accounts",
        "path": "/crm/accounts",
        "label": "Accounts"
      },
      {
        "key": "crm.leads",
        "path": "/crm/leads",
        "label": "Leads"
      },
      {
        "key": "crm.pipeline",
        "path": "/crm/pipeline",
        "label": "Pipeline"
      },
      {
        "key": "crm.forecast",
        "path": "/crm/forecast",
        "label": "Forecast"
      },
      {
        "key": "crm.activities",
        "path": "/crm/activities",
        "label": "Activities"
      },
      {
        "key": "crm.tickets",
        "path": "/crm/tickets",
        "label": "Tickets"
      },
      {
        "key": "crm.canned-responses",
        "path": "/crm/canned-responses",
        "label": "Canned Responses"
      },
      {
        "key": "crm.customer-tiers",
        "path": "/crm/customer-tiers",
        "label": "Customer Tiers"
      },
      {
        "key": "crm.integrations",
        "path": "/crm/integrations",
        "label": "Integrations"
      },
      {
        "key": "crm.settings.pipelines",
        "path": "/crm/settings/pipelines",
        "label": "Settings"
      }
    ]
  },
  {
    "module": "Project Management",
    "pages": [
      {
        "key": "projects.dashboard",
        "path": "/projects/dashboard",
        "label": "Dashboard"
      },
      {
        "key": "projects.projects",
        "path": "/projects/projects",
        "label": "Projects"
      },
      {
        "key": "projects.work-orders",
        "path": "/projects/work-orders",
        "label": "Work Orders"
      },
      {
        "key": "projects.tasks",
        "path": "/projects/tasks",
        "label": "Tasks"
      },
      {
        "key": "projects.schedule",
        "path": "/projects/schedule",
        "label": "Schedule"
      },
      {
        "key": "projects.milestones",
        "path": "/projects/milestones",
        "label": "Milestones"
      }
    ]
  },
  {
    "module": "Marketing & Affiliates",
    "pages": [
      {
        "key": "marketing.dashboard",
        "path": "/marketing/dashboard",
        "label": "Overview"
      },
      {
        "key": "marketing.segments",
        "path": "/marketing/segments",
        "label": "Segments"
      },
      {
        "key": "marketing.email-connectors",
        "path": "/marketing/email-connectors",
        "label": "Email Connectors"
      },
      {
        "key": "marketing.email-campaigns",
        "path": "/marketing/email-campaigns",
        "label": "Email Campaigns"
      },
      {
        "key": "marketing.campaigns",
        "path": "/marketing/campaigns",
        "label": "Campaigns"
      },
      {
        "key": "marketing.coupons",
        "path": "/marketing/coupons",
        "label": "Coupons"
      },
      {
        "key": "marketing.affiliates",
        "path": "/marketing/affiliates",
        "label": "Affiliates"
      }
    ]
  },
  {
    "module": "Social Media",
    "pages": [
      {
        "key": "social.dashboard",
        "path": "/social/dashboard",
        "label": "Overview"
      },
      {
        "key": "social.compose",
        "path": "/social/compose",
        "label": "Composer"
      },
      {
        "key": "social.posts",
        "path": "/social/posts",
        "label": "Posts"
      },
      {
        "key": "social.messages",
        "path": "/social/messages",
        "label": "Inbox"
      },
      {
        "key": "social.ads",
        "path": "/social/ads",
        "label": "Ads"
      },
      {
        "key": "social.insights",
        "path": "/social/insights",
        "label": "Insights"
      },
      {
        "key": "social.accounts",
        "path": "/social/accounts",
        "label": "Accounts"
      },
      {
        "key": "social.creators",
        "path": "/social/creators",
        "label": "Creators"
      }
    ]
  }
];
